import Link from 'next/link'
import '../globals.css'
import { Rajdhani } from 'next/font/google'

const inter = Rajdhani({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700']
})

export const metadata = {
  title: 'My Awesome Site',
  description: 'Generated by Next + Sanity',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-3xl mx-auto py-10`}>
      <header>
        <Link href='/' className='bg-gradient-to-r 
          from-blue-500 
          to-red-400 
          bg-clip-text 
          text-transparent text-2xl font-bold'>
          iR
        </Link>
      </header>
      <main className='py-20'>{children}</main>
      </body>
    </html>
  )
}
